# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

In [2]:
array1 = np.arange(10).reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
x = np.arange(10).reshape(2,5)
y = np.ones(10, dtype = 'int').reshape(2,5)
np.vstack((x,y))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
a = np.arange(10).reshape(2,5)
b = np.ones(10, dtype='int').reshape(2,5)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
arr = np.arange(10).reshape(1,5,2) 
arr.flatten() 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [6]:
arr_3d = np.arange(15).reshape(1,3,5)
arr_3d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [7]:
ar1 = np.arange(15)
ar1.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [8]:
arr7 = np.arange(25).reshape(5,5)
print(arr7)
np.square(arr7)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [9]:
arr8 = np.arange(30).reshape(5,6)
print(arr8)
np.mean(arr8)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [10]:
np.std(arr8)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [11]:
np.median(arr8)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [12]:
np.transpose(arr8)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [13]:
arr12 = np.arange(16).reshape(4,4)
print(arr12)
np.trace(arr12)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [14]:
np.linalg.det(arr12)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [15]:
arr14 = np.array([2,4,6,8,10,12,14,16,18,20])
print(np.percentile(arr14,5))
print(np.percentile(arr14,95))

2.9000000000000004
19.099999999999998


## Question:15

### How to find if a given array has any null values?

In [16]:
arr15 = np.array([5,0,6,9,0,13,0])
np.isnan(arr15)

array([False, False, False, False, False, False, False])